const loggedOutPages = [
  { "Name": "Home", "NavigateTo": "/" },
  { "Name": "Login or Signup", "NavigateTo": "/login" },
];

const loggedInPages = [
  { "Name": "Dashboard", "NavigateTo": "/dashboard" },
  { "Name": "Profile", "NavigateTo": "/profile" },
  { "Name": "Logout", "NavigateTo": "/logout" },
];

const rnaTestSequences = [
  {"id": 1, "Name": "Virus: HIV-1 - tat", "RNASequence": "AUGUUCUAUCAGAUGUAUGCUGUUCUCAUACUUAUGUUAUGCUUGUUGAUUAUUCCUAAAUAGUAUUUUUCUGUUCAGUUGUGACUAUUUGUAUCUCAAUCUUGUCUAUCUACUUCUGUUCAGUUGUGACUAUUUGUAAAUAGUAUUUUUCUGUUCAGUUGUGACUAUUUGUAUCUCAAUCUUGUCUAUCUACUUCUGUUCAGUUGUGACUAUUUGUAAAUAGUAUUUUUCUGUUCAGUUGUGACUAUUUGUAUCUCAAUCUUGUCUAUCUACUUCUGUUCAGUUGUGACUAUUUGUAAAUAGUAUUUUUCUGUUCAGU" },
  {"id": 2, "Name": "Virus: HCV - NS5B", "RNASequence": "GUUUAUUGUACAUGUGCUUUGCCUUAUCAUGUGUUGUUAAUCUACUAUCCUAGUAUCUUCUUGUAGUAUAUAUUAUGGUUAUCCUUAUAUUCUGUUUAUUGUGUACAUGUGCUUUGCCUUAUCAUGUGUUGUUAAUCUACUAUCCUAGUAUCUUCUUGUAGUAUAUAUUAUGGUUAUCCUUAUAUUCUGUUUAUUGUGUACAUGUGCUUUGCCUUAUCAUGUGUUGUUAAUCUACUAUCCUAGUAUCUUCUUGUAGUAUAUAUUAUGGUUAUCCUUAUAUUCUGUUUAUUGUGUACAUGUGCUUUGCCUUAUCAUGUGUUGUUAAUCUACUAUCCUAGUAUCUUCUUGUAGUAUAUAUUAUGGUUAUCCUUAUAUUCUGUUUAUUGUGUACAUGUGCUUUGCCUUAUCAUGUGUUGUUAAUCUACUAUCCUAGUAUCUUCUUGUAGUAUAUAUUAUGGUUAUCCUUAUAUUCUGUUU" },
  {"id": 3, "Name": "Virus: IAV - HA", "RNASequence": "GAUUCUGACUACUUGUCUGAUUUUUAUUUUCUCUCAUUUGUUGAUUCCUUCUACCUAUGAUAUCCAUUGUUGAUAUUUCUGCGUGUGAUAUGCUCUGAUUUUUUGUAGAUAUUCCAUUGUUGAUAUUUCUGCGUGUGAUAUGCUCUGAUUUUUUGUAGAUAUUCCAUUGUUGAUAUUUCUGCGUGUGAUAUGCUCUGAUUUUUUGUAGAUAUUCCAUUGUUGAUAUUUCUGCGUGUGAUAUGCUCUGAUUUUUUGUAGAUAUUCCAUUGUUGAUAUUUCUGCGUGUGAUAUGCUCUGAUUUUUUGUAGAUAUUCCAUUGUUG" },
  {"id": 4, "Name": "Bacteria: E. coli - 16S rRNA", "RNASequence": "GCUUUAUGAUCUUAAUACUUCUUUUUGCGUUCUAGUAGUUUACUUUCCUUAUCAUGUUGUACUUCUAUUUCCUUAUGUAUAUCAUAUAUGUGUACUAUUAUAUUGUGCUUUAUGAUCUUAAUACUUCUUUUUGCGUUCUAGUAGUUUACUUUCCUUAUCAUGUUGUACUUCUAUUUCCUUAUGUAUAUCAUAUAUGUGUACUAUUAUAUUGUGCUUUAUGAUCUUAAUACUUCUUUUUGCGUUCUAGUAGUUUACUUUCCUUAUCAUGUUGUACUUCUAUUUCCUUAUGUAUAUCAUAUAUGUGUACUAUUAUAUUGUGCUU" },
  {"id": 5, "Name": "Bacteria: Bacillus subtilis - flagellin", "RNASequence": "GUUUGUUGUUAAUCUUAUACGAUGAUUAGUAUACGUCGUCUCCUAGUGUCAUAUCCUUUGUGUCUUGUCAUAUCCUUUGUGUCAUAU" },
];

export { loggedInPages, loggedOutPages, rnaTestSequences };