const loggedOutPages = [
  { "Name": "Home", "NavigateTo": "/" },
  { "Name": "Login or Signup", "NavigateTo": "/login" },
];

const loggedInPages = [
  { "Name": "Dashboard", "NavigateTo": "/dashboard" },
  { "Name": "Profile", "NavigateTo": "/profile" },
  { "Name": "Logout", "NavigateTo": "/logout" },
];

const rnaTestSequences = [
  {"id": 1, "rna_name": "Virus: HIV-1 - tat", "rna_sequence": "AUGUUCUAUCAGAUGUAUGCUGUUCUCAUACUUAUGUUAUGCUUGUUGAUUAUUCCUAAAUAGUAUUUUUCUGUUCAGUUGUGACUAUUUGUAUCUCAAUCUUGUCUAUCUACUUCUGUUCAGUUGUGACUAUUUGUAAAUAGUAUUUUUCUGUUCAGUUGUGACUAUUUGUAUCUCAAUCUUGUCUAUCUACUUCUGUUCAGUUGUGACUAUUUGUAAAUAGUAUUUUUCUGUUCAGUUGUGACUAUUUGUAUCUCAAUCUUGUCUAUCUACUUCUGUUCAGUUGUGACUAUUUGUAAAUAGUAUUUUUCUGUUCAGU" },
  {"id": 2, "rna_name": "Virus: HCV - NS5B", "rna_sequence": "GUUUAUUGUACAUGUGCUUUGCCUUAUCAUGUGUUGUUAAUCUACUAUCCUAGUAUCUUCUUGUAGUAUAUAUUAUGGUUAUCCUUAUAUUCUGUUUAUUGUGUACAUGUGCUUUGCCUUAUCAUGUGUUGUUAAUCUACUAUCCUAGUAUCUUCUUGUAGUAUAUAUUAUGGUUAUCCUUAUAUUCUGUUUAUUGUGUACAUGUGCUUUGCCUUAUCAUGUGUUGUUAAUCUACUAUCCUAGUAUCUUCUUGUAGUAUAUAUUAUGGUUAUCCUUAUAUUCUGUUUAUUGUGUACAUGUGCUUUGCCUUAUCAUGUGUUGUUAAUCUACUAUCCUAGUAUCUUCUUGUAGUAUAUAUUAUGGUUAUCCUUAUAUUCUGUUUAUUGUGUACAUGUGCUUUGCCUUAUCAUGUGUUGUUAAUCUACUAUCCUAGUAUCUUCUUGUAGUAUAUAUUAUGGUUAUCCUUAUAUUCUGUUU" },
  {"id": 3, "rna_name": "Virus: IAV - HA", "rna_sequence": "GAUUCUGACUACUUGUCUGAUUUUUAUUUUCUCUCAUUUGUUGAUUCCUUCUACCUAUGAUAUCCAUUGUUGAUAUUUCUGCGUGUGAUAUGCUCUGAUUUUUUGUAGAUAUUCCAUUGUUGAUAUUUCUGCGUGUGAUAUGCUCUGAUUUUUUGUAGAUAUUCCAUUGUUGAUAUUUCUGCGUGUGAUAUGCUCUGAUUUUUUGUAGAUAUUCCAUUGUUGAUAUUUCUGCGUGUGAUAUGCUCUGAUUUUUUGUAGAUAUUCCAUUGUUGAUAUUUCUGCGUGUGAUAUGCUCUGAUUUUUUGUAGAUAUUCCAUUGUUG" },
  {"id": 4, "rna_name": "Bacteria: E. coli - 16S rRNA", "rna_sequence": "GCUUUAUGAUCUUAAUACUUCUUUUUGCGUUCUAGUAGUUUACUUUCCUUAUCAUGUUGUACUUCUAUUUCCUUAUGUAUAUCAUAUAUGUGUACUAUUAUAUUGUGCUUUAUGAUCUUAAUACUUCUUUUUGCGUUCUAGUAGUUUACUUUCCUUAUCAUGUUGUACUUCUAUUUCCUUAUGUAUAUCAUAUAUGUGUACUAUUAUAUUGUGCUUUAUGAUCUUAAUACUUCUUUUUGCGUUCUAGUAGUUUACUUUCCUUAUCAUGUUGUACUUCUAUUUCCUUAUGUAUAUCAUAUAUGUGUACUAUUAUAUUGUGCUU" },
  {"id": 5, "rna_name": "Bacteria: Bacillus subtilis - flagellin", "rna_sequence": "GUUUGUUGUUAAUCUUAUACGAUGAUUAGUAUACGUCGUCUCCUAGUGUCAUAUCCUUUGUGUCUUGUCAUAUCCUUUGUGUCAUAU" },
];

export { loggedInPages, loggedOutPages, rnaTestSequences };